---
# paths --
path:
    data_path_poi1: ../data/base_poi/
    data_path_poi2: ../data/poi2/
    data_path_brp: ../data/BRP/
    output_path: ../output/
    data_stag_tables: ../data/stag_tables/
    distance_matrices: ../data/distance_matrices/


# files --
file:
    bag_full : 'bag_full.csv'
    bag_clusters: 'bag_cluster.csv'
    ah : 'ah_vestigingen.csv'
    oba : 'oba_vestigingen.csv'
    vot18: 'stag_adres18.csv'
    vot65: 'stag_adres65.csv'

file_stag_tables:
    clusters18: 'vot_clusters_18.csv'
    clusters65: 'vot_clusters_65.csv'
    clusters_huur: 'vot_clusters_huur.csv'
    clusters_koop: 'vot_clusters_koop.csv'
    inzamelloc: 'inzamelloc.csv'
    
distance_matrix_files:
    distance_huur_papier: 'distance_huur_Papier.csv'
    distance_huur_glas: 'distance_huur_Glas.csv'
    distance_huur_textiel: 'distance_huur_Textiel.csv'
    distance_huur_plastic: 'distance_huur_Plastic.csv'
    distance_huur_rest: 'distance_huur_Rest.csv'
    distance_koop_papier: 'distance_koop_Papier.csv'
    distance_koop_glas: 'distance_koop_Glas.csv'
    distance_koop_textiel: 'distance_koop_Textiel.csv'
    distance_koop_plastic: 'distance_koop_Plastic.csv'
    distance_koop_rest: 'distance_koop_Rest.csv'

# crs --    
crs:
    crs_4326: {'init' : 'epsg:4326'}
    crs : {'init': 'epsg:28992'}

# get Bammenservice afvalcontainers GeoJson
afvalcontainers:
    url: 'https://map.data.amsterdam.nl/maps/afval?REQUEST=GetFeature'
    # parameters for afvalcontainer WFS found at api.data.amsterdam.nl
    params:
     Typename: 'ms:container_coordinaten'
     SERVICE: 'wfs'
     version: '1.1.0'
     outputFormat: 'GeoJson'
     srsname: 'epsg:4326'
    fracties: ['Rest', 'Papier', 'Glas', 'Plastic', 'Textiel']

# parameters DBSCAN algorithm afvalcontainers
dbscan_afvalcontainers:
    params:
     eps: 9
     min_samples: 1
     algorithm: 'ball_tree'
     metric: 'euclidean'

# parameters DBSCAN algorithm verblijfsobjecten (VOT)
dbscan_vot:
    params:
     eps: 2.5
     min_samples: 1
     algorithm: 'ball_tree'
     metric: 'euclidean'

# afstandsnormen Gemeente Amsterdam per fractie
normen:
    Papier:
     doel_start: 0
     doel_end: 200
     aandacht_start: 200
     aandacht_end: 300
     kritiek_start: 300
     bovengrens: 301
    Glas:
     doel_start: 0
     doel_end: 300
     aandacht_start: 300
     aandacht_end: 400
     kritiek_start: 400
     bovengrens: 401
    Plastic:
     doel_start: 0
     doel_end: 250
     aandacht_start: 250
     aandacht_end: 350
     kritiek_start: 350
     bovengrens: 351
    Textiel:
     doel_start: 0
     doel_end: 750
     aandacht_start: 750
     aandacht_end: 1500
     kritiek_start: 1500
     bovengrens: 1501
    Rest:
     doel_start: 0
     doel_end: 100
     aandacht_start: 100
     aandacht_end: 200
     kritiek_start: 200
     bovengrens: 201

vot_koop_huur: ['koop', 'huur']
stadsdeel: ['Centrum', 'West', 'Nieuw-West', 'Zuid', 'Oost', 'Noord', 'Zuidoost']  
buurtcombi : ['Staatsliedenbuurt',
              'Da Costabuurt',
              'Burgwallen-Oude Zijde',
              'Grachtengordel-Zuid',
              'Nieuwmarkt/Lastage',
              'Haarlemmerbuurt',
              'De Weteringschans',
              'Van Galenbuurt',
              'Hoofdweg e.o.',
              'Overtoomse Sluis',
              'Westindische Buurt',
              'Slotermeer-Noordoost',
              'Slotermeer-Zuidwest',
              'Geuzenveld',
              'Eendracht',
              'Osdorp-Oost',
              'Osdorp-Midden',
              'De Punt',
              'Helmersbuurt',
              'IJselbuurt',
              'Overtoomse Veld',
              'Westlandgracht',
              'Kinkerbuurt',
              'Van Lennepbuurt',
              'Vondelbuurt',
              'Oude Pijp',
              'Nieuwe Pijp',
              'Hoofddorppleinbuurt',
              'Schinkelbuurt',
              'Willemspark',
              'Museumkwartier',
              'Apollobuurt',
              'Rijnbuurt',
              'Weesperzijde',
              'Oosterparkbuurt',
              'Transvaalbuurt',
              'Tuindorp Buiksloot',
              'Nieuwendammerdijk/Buiksloterdijk',
              'Indische Buurt West',
              'Oostzanerwerf',
              'Indische Buurt Oost',
              'Oostelijk Havengebied',
              'Middenmeer',
              'Betondorp',
              'Volewijck',
              'IJplein/Vogelbuurt',
              'Tuindorp Nieuwendam',
              'Tuindorp Oostzaan',
              'Waterland',
              'Lutkemeer/Ookmeer',
              'Bijlmer Centrum (D,F,H)',
              'Sloter-/Riekerpolder',
              'Frederik Hendrikbuurt',
              'Amstel III/Bullewijk',
              'Gein',
              'Driemond',
              'Burgwallen-Nieuwe Zijde',
              'Zuidas',
              'Slotervaart Zuid',
              'Grachtengordel-West',
              'Stadionbuurt',
              'Scheldebuurt',
              'Dapperbuurt',
              'Zeeburgereiland/Nieuwe Diep',
              'Jordaan',
              'Weesperbuurt/Plantage',
              'Oostelijke Eilanden/Kadijken',
              'Westelijk Havengebied',
              'Buitenveldert-West',
              'Buitenveldert-Oost',
              'Houthavens',
              'Sloterdijk',
              'Spaarndammer- en Zeeheldenbuurt',
              'Centrale Markt',
              'IJburg Oost',
              'Landlust',
              'Erasmuspark',
              'Geuzenbuurt',
              'De Kolenkit',
              'Chassébuurt',
              'Bedrijventerrein Sloterdijk',
              'IJburg West',
              'Middelveldsche Akerpolder',
              'Slotervaart Noord',
              'Zuid Pijp',
              'Prinses Irenebuurt e.o.',
              'Omval/Overamstel',
              'Waterlandpleinbuurt',
              'Noordelijke IJ-oevers West',
              'Noordelijke IJ-oevers Oost',
              'IJburg Zuid',
              'Frankendael',
              'Kadoelen',
              'Buikslotermeer',
              'Banne Buiksloot',
              'Elzenhagen',
              'Bijlmer Oost (E,G,K)',
              'Nellestein',
              'Holendrecht/Reigersbos']

